In [24]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [25]:
medical = pd.read_excel("../data/interim/transformed_insurance.xlsx")
medical.head()

,Unnamed: 0,age,bmi,children,expenses,sex_female,sex_male,smoker_no,smoker_yes,age_smoker
0,0,19,27.9,0,16884.92,1,0,0,1,19
1,1,18,33.8,1,1725.55,0,1,1,0,0
2,2,28,33.0,3,4449.46,0,1,1,0,0
3,3,33,22.7,0,21984.47,0,1,1,0,0
4,4,32,28.9,0,3866.86,0,1,1,0,0

In [26]:
medical = medical.drop(columns=["children"], axis=0)

In [27]:
medical.head()

,Unnamed: 0,age,bmi,expenses,sex_female,sex_male,smoker_no,smoker_yes,age_smoker
0,0,19,27.9,16884.92,1,0,0,1,19
1,1,18,33.8,1725.55,0,1,1,0,0
2,2,28,33.0,4449.46,0,1,1,0,0
3,3,33,22.7,21984.47,0,1,1,0,0
4,4,32,28.9,3866.86,0,1,1,0,0

In [28]:
x = medical.drop(columns=["expenses"])
y= medical["expenses"]

In [30]:
x = x.drop(columns=["Unnamed: 0"])

In [31]:
x

      age   bmi  sex_female  sex_male  smoker_no  smoker_yes  age_smoker
0      19  27.9           1         0          0           1          19
1      18  33.8           0         1          1           0           0
2      28  33.0           0         1          1           0           0
3      33  22.7           0         1          1           0           0
4      32  28.9           0         1          1           0           0
...   ...   ...         ...       ...        ...         ...         ...
1332   50  31.0           0         1          1           0           0
1333   18  31.9           1         0          1           0           0
1334   18  36.9           1         0          1           0           0
1335   21  25.8           1         0          1           0           0
1336   61  29.1           1         0          0           1          61

[1337 rows x 7 columns]

In [32]:
y

0       16884.92
1        1725.55
2        4449.46
3       21984.47
4        3866.86
          ...
1332    10600.55
1333     2205.98
1334     1629.83
1335     2007.95
1336    29141.36
Name: expenses, Length: 1337, dtype: float64

In [33]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2,)

In [34]:
medical.to_excel("../data/processed/ml-ready-data.xlsx")

In [35]:
print("x_train:",x_train.shape)
print("y_train:",y_train.shape)
print("x_test:", x_test.shape)
print("y_test:", y_test.shape)

x_train: (1069, 7)
y_train: (1069,)
x_test: (268, 7)
y_test: (268,)