In [142]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.linear_model import ElasticNet
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

In [6]:
file_path = "../data/processed/ml-ready-data.xlsx"
medical = pd.read_excel(file_path)
medical.head()

,Unnamed: 0.1,Unnamed: 0,age,bmi,expenses,sex_female,sex_male,smoker_no,smoker_yes,age_smoker
0,0,0,19,27.9,16884.92,1,0,0,1,19
1,1,1,18,33.8,1725.55,0,1,1,0,0
2,2,2,28,33.0,4449.46,0,1,1,0,0
3,3,3,33,22.7,21984.47,0,1,1,0,0
4,4,4,32,28.9,3866.86,0,1,1,0,0

In [7]:
medical = medical.drop(columns=["Unnamed: 0.1","Unnamed: 0"])

In [8]:
x = medical.drop(columns=["expenses"])
x.head()

   age   bmi  sex_female  sex_male  smoker_no  smoker_yes  age_smoker
0   19  27.9           1         0          0           1          19
1   18  33.8           0         1          1           0           0
2   28  33.0           0         1          1           0           0
3   33  22.7           0         1          1           0           0
4   32  28.9           0         1          1           0           0

In [9]:
y = medical["expenses"]
y.head()

0    16884.92
1     1725.55
2     4449.46
3    21984.47
4     3866.86
Name: expenses, dtype: float64

In [10]:
x_train, x_test, y_train, y_test = train_test_split(
    x,
    y,
    train_size= 0.8,
    random_state=42
)

In [11]:
print("x_train:",x_train.shape)
print("x_test:",x_test.shape)

print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

x_train: (1069, 7)
x_test: (268, 7)
y_train: (1069,)
y_test: (268,)

In [12]:
model = LinearRegression()

In [75]:
print(model.coef_)
print(model.intercept_)

[-5.61133902e-08 -5.92766303e+01 -6.40901480e+02  1.22883120e+03
 -1.22883121e+03  1.91032085e+03 -1.91032085e+03 -3.44805269e+01
  4.13204856e+00  7.56528721e-01 -7.92562386e+01  1.99796083e+01
 -2.47961034e+01 -3.44805269e+01 -1.66676707e+00  4.66984821e+01
 -3.69124742e+02 -2.71776737e+02 -5.04525189e+02 -1.36376290e+02
  1.10581082e+01  1.22883121e+03 -2.43289833e-11  9.82145617e+02
  2.46685588e+02 -5.32559727e+01 -1.22883121e+03  9.28175229e+02
 -2.15700643e+03  1.87754458e+01  1.91032085e+03  0.00000000e+00
  0.00000000e+00 -1.91032085e+03 -3.44805269e+01 -1.66676705e+00
 -7.53806585e-02  9.53808014e-03  2.80199113e+00  1.33005744e+00
  5.79881561e+00 -1.66676705e+00  5.20184050e-02  1.32575825e-01
  2.60143475e+00 -1.84490602e+00 -1.03015795e+01  1.10581082e+01
 -8.39432286e-02 -7.92562386e+01  0.00000000e+00 -2.60002659e+01
 -5.32559727e+01 -1.26562867e+00  1.99796083e+01  1.20416252e+00
  1.87754458e+01 -4.01138380e-01 -2.47961034e+01  0.00000000e+00
  0.00000000e+00 -3.44805269e+01 -1.66676705e+00  5.20184332e-02
 -1.05924229e+00  2.25304696e+01  2.41680125e+01  2.22542863e+01
  2.44441958e+01 -4.74042945e-01 -3.69124742e+02  0.00000000e+00
 -2.28419864e+02 -1.40704878e+02  1.06228449e+01 -2.71776737e+02
 -2.76105325e+02  4.32858736e+00  4.35263344e-01 -5.04525189e+02
  0.00000000e+00  0.00000000e+00 -1.36376290e+02  1.10581082e+01
 -8.39432072e-02  1.22883121e+03  0.00000000e+00  9.82145617e+02
  2.46685588e+02 -5.32559727e+01  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  9.82145617e+02  0.00000000e+00
  0.00000000e+00  2.46685588e+02 -5.32559727e+01 -1.26562867e+00
 -1.22883121e+03  9.28175229e+02 -2.15700643e+03  1.87754458e+01
  9.28175229e+02  0.00000000e+00  0.00000000e+00 -2.15700643e+03
  1.87754458e+01 -4.01138380e-01  1.91032085e+03  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
 -1.91032085e+03 -3.44805269e+01 -1.66676705e+00  5.20184332e-02]
19847.824394575695

In [14]:
model.fit(x_train,y_train)

LinearRegression()

In [15]:
print("intercept:", model.intercept_)
print("cofficients:", model.coef_)
print("no.of feature after training:", model.n_features_in_)

intercept: 397.81242480364745
cofficients: [   245.87059888    306.52380437     47.26908813    -47.26908813
 -10985.38117207  10985.38117207     28.99245688]
no.of feature after training: 7

In [16]:
for feature, coefficient in zip(x_train.columns, model.coef_):
    print(feature, ":", coefficient)
print("intercept:", model.intercept_)

age : 245.87059887600117
bmi : 306.52380437286763
sex_female : 47.26908812747785
sex_male : -47.26908812747403
smoker_no : -10985.38117207363
smoker_yes : 10985.381172073634
age_smoker : 28.992456875693428
intercept: 397.81242480364745

In [17]:
y_pred = model.predict(x_test)

In [18]:
mae = mean_absolute_error(y_test,y_pred)
mse = mean_squared_error(y_test,y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test,y_pred)

In [19]:
print("MEAN ABSOLUTE ERROR:",mae)
print("MEAN SQUARED ERROR:",mse)
print("ROOT MEAN SQUARED ERROR:",rmse)
print("R-SQUARED:",r2)

MEAN ABSOLUTE ERROR: 4185.615792671464
MEAN SQUARED ERROR: 35630942.83585221
ROOT MEAN SQUARED ERROR: 5969.166008401192
R-SQUARED: 0.8060965108441581

In [20]:
predication = model.predict(x_test.iloc[[5,6,7]])
print(predication[2])
print(y_test.iloc[7])

2317.3819623902036
2150.47

In [21]:
model_error = predication[2] - y_test.iloc[7]
model_error

np.float64(166.91196239020383)

In [51]:
results = []
results.append(
    {
        "model" : "LinearRegression",
        "MAE" : mae,
        "MSE" : mse,
        "RMSE": rmse,
        "trainR2": r2,
        "testR2": r2
        }
)

results_df = pd.DataFrame(results)
results_df

,model,MAE,MSE,RMSE,trainR2,testR2
0,LinearRegression,2938.211584,2.355099e+07,4852.936554,0.806097,0.806097

In [23]:
# Polynomial regression
poly = PolynomialFeatures(degree=2)

x_train_poly = poly.fit_transform(x_train)
x_test_poly = poly.transform(x_test)

model = LinearRegression()

model.fit(x_train_poly,y_train)

LinearRegression()

In [77]:
y_train_poly = model.predict(x_train_poly)
y_test_poly = model.predict(x_test_poly)

for feature, coefficient in zip(x_train.columns,model.coef_):
    print(feature, ":", coefficient)

age : -5.6113390174500354e-08
bmi : -59.27663026203904
sex_female : -640.9014795461665
sex_male : 1228.8312049763003
smoker_no : -1228.8312052087213
smoker_yes : 1910.3208461351107
age_smoker : -1910.3208459982675

In [ ]:
mae = mean_absolute_error(y_test,y_test_poly)
mse = mean_squared_error(y_test,y_test_poly)
rmse = np.sqrt(mse)
train_r2_poly = r2_score(y_train,y_train_poly)
test_r2_poly = r2_score(y_test,y_test_poly)

In [26]:
print(mae)
print(mse)
print(rmse)
print(r2)

2841.6269271110045
21351707.91260414
4620.790831946858
0.8060965108441581

In [71]:
results.append({
    "model": "Polynomial regression-DEGREE 2",
    "MAE":mae,
    "MSE": mse,
    "RMSE": rmse,
    "trainR2" : train_r2_poly,
    "testR2": test_r2_poly
})
results_df = pd.DataFrame(results)
results_df

,model,MAE,MSE,RMSE,trainR2,testR2
0,LinearRegression,2938.211584,2.355099e+07,4852.936554,0.806097,0.806097
1,Polynomial regression-DEGREE 2,2938.211584,2.355099e+07,4852.936554,0.824568,0.883804
2,polynomial regression degree -3,2938.211584,2.355099e+07,4852.936554,0.827988,0.882396
3,polynomial regression degree -3,2938.211584,2.355099e+07,4852.936554,0.827988,0.882396
4,polynomial regression degree -3,2925.988340,2.161038e+07,4648.696938,0.827988,0.882396
5,polynomial regression degree -3,2925.988340,2.161038e+07,4648.696938,0.827988,0.882396
6,polynomial regression degree -3,2925.988340,2.161038e+07,4648.696938,0.827988,0.882396
7,Polynomial regression-DEGREE 2,2925.988340,2.161038e+07,4648.696938,0.824568,0.883804

In [28]:
result_df.drop(result_df.index[[1,3,4]])

IndexError: index 4 is out of bounds for axis 0 with size 2

In [ ]:
# polnomial degree-3
polyn = PolynomialFeatures(degree=3)
x_train_poly = polyn.fit_transform(x_train)
x_test_poly = polyn.transform(x_test)

In [ ]:
model1 = LinearRegression()
model1.fit(x_train_poly,y_train)
y_train_pred_poly = model1.predict(x_train_poly)
y_test_pred_poly = model1.predict(x_test_poly)

for feature, coefficients in zip(x_train.columns, model1.coef_):
    print(feature, ":", coefficients)

age : -5.6113390174500354e-08
bmi : -59.27663026203904
sex_female : -640.9014795461665
sex_male : 1228.8312049763003
smoker_no : -1228.8312052087213
smoker_yes : 1910.3208461351107
age_smoker : -1910.3208459982675

In [58]:
mae = mean_absolute_error(y_test,y_test_pred_poly)
mse = mean_squared_error(y_test,y_test_pred_poly)
rmse = np.sqrt(mse)
trained_r2 = r2_score(y_train,y_train_pred_poly)
tested_r2 = r2_score(y_test,y_test_pred_poly)

In [59]:
print(mae)
print(mse)
print(rmse)
print(trained_r2)
print(tested_r2)

2925.9883396198666
21610383.222040653
4648.696938072071
0.8279878017191966
0.8823963562218119

In [63]:
results.append({
    "model":"polynomial regression degree -3",
    "MAE":mae,
    "MSE": mse,
    "RMSE": rmse,
    "trainR2": trained_r2,
    "testR2": tested_r2
})
results_df = pd.DataFrame(results)
results_df

,model,MAE,MSE,RMSE,trainR2,testR2
0,LinearRegression,2938.211584,2.355099e+07,4852.936554,0.806097,0.806097
1,Polynomial regression-DEGREE 2,2938.211584,2.355099e+07,4852.936554,0.824568,0.883804
2,polynomial regression degree -3,2938.211584,2.355099e+07,4852.936554,0.827988,0.882396
3,polynomial regression degree -3,2938.211584,2.355099e+07,4852.936554,0.827988,0.882396
4,polynomial regression degree -3,2925.988340,2.161038e+07,4648.696938,0.827988,0.882396
5,polynomial regression degree -3,2925.988340,2.161038e+07,4648.696938,0.827988,0.882396
6,polynomial regression degree -3,2925.988340,2.161038e+07,4648.696938,0.827988,0.882396

In [67]:
results_df

,model,MAE,MSE,RMSE,trainR2,testR2
0,LinearRegression,2938.211584,2.355099e+07,4852.936554,0.806097,0.806097
1,Polynomial regression-DEGREE 2,2938.211584,2.355099e+07,4852.936554,0.824568,0.883804
2,polynomial regression degree -3,2938.211584,2.355099e+07,4852.936554,0.827988,0.882396
3,polynomial regression degree -3,2938.211584,2.355099e+07,4852.936554,0.827988,0.882396
4,polynomial regression degree -3,2925.988340,2.161038e+07,4648.696938,0.827988,0.882396
5,polynomial regression degree -3,2925.988340,2.161038e+07,4648.696938,0.827988,0.882396
6,polynomial regression degree -3,2925.988340,2.161038e+07,4648.696938,0.827988,0.882396

In [70]:
results_df.drop(results_df.index[3:7])

,model,MAE,MSE,RMSE,trainR2,testR2
0,LinearRegression,2938.211584,2.355099e+07,4852.936554,0.806097,0.806097
1,Polynomial regression-DEGREE 2,2938.211584,2.355099e+07,4852.936554,0.824568,0.883804
2,polynomial regression degree -3,2938.211584,2.355099e+07,4852.936554,0.827988,0.882396

In [79]:
for feature, coefficients in zip(x_train.columns, model1.coef_):
    print(feature, ":", coefficients)
print("intercept:", model1.intercept_)

age : -5.6113390174500354e-08
bmi : -59.27663026203904
sex_female : -640.9014795461665
sex_male : 1228.8312049763003
smoker_no : -1228.8312052087213
smoker_yes : 1910.3208461351107
age_smoker : -1910.3208459982675
intercept: 19847.824394575695

In [122]:
# ridge regression
Ridge_model = Ridge(alpha=1.0)

# model training
Ridge_model.fit(x_train, y_train)

# testing/prediction
Ridge_pred_train = Ridge_model.predict(x_train)
Ridge_pred_test = Ridge_model.predict(x_test)

In [123]:
for feature, coefficient in zip(x_train.columns, Ridge_model.coef_):
    print(feature, ":", coefficient)

age : 243.3120956098526
bmi : 306.9425343645384
sex_female : 46.97500621318446
sex_male : -46.975006213159965
smoker_no : -10718.016049976308
smoker_yes : 10718.016049976068
age_smoker : 41.29152220828799

In [124]:
#  model evaluation
mae = mean_absolute_error(y_test,Ridge_pred_test)
mse = mean_squared_error(y_test, Ridge_pred_test)
rmse = np.sqrt(mse)
trained_r2 = r2_score(y_train,Ridge_pred_train)
tested_r2 = r2_score(y_test,Ridge_pred_test)

In [125]:
print(mae)
print(mse)
print(rmse)
print(trained_r2)
print(tested_r2)

4191.047579974365
35637815.502769254
5969.741661309076
0.7264025255888227
0.806059109810423

In [126]:
results_df

,model,MAE,MSE,RMSE,trainR2,testR2
0,LinearRegression,2938.211584,2.355099e+07,4852.936554,0.806097,0.806097
1,Polynomial regression-DEGREE 2,2938.211584,2.355099e+07,4852.936554,0.824568,0.883804
2,polynomial regression degree -3,2938.211584,2.355099e+07,4852.936554,0.827988,0.882396
3,polynomial regression degree -3,2938.211584,2.355099e+07,4852.936554,0.827988,0.882396
4,polynomial regression degree -3,2925.988340,2.161038e+07,4648.696938,0.827988,0.882396
5,polynomial regression degree -3,2925.988340,2.161038e+07,4648.696938,0.827988,0.882396
6,polynomial regression degree -3,2925.988340,2.161038e+07,4648.696938,0.827988,0.882396
7,Polynomial regression-DEGREE 2,2925.988340,2.161038e+07,4648.696938,0.824568,0.883804

In [139]:
# lasso regreesion
lasso_model = Lasso(alpha=1.0)

lasso_model.fit(x_train,y_train)

lasso_train_pred = lasso_model.predict(x_train)
laaso_test_pred = lasso_model.predict(x_test)

In [140]:
mea = mean_absolute_error(y_test,laaso_test_pred)
mse = mean_squared_error(y_test, laaso_test_pred)
rmse = np.sqrt(mse)
trained_r2 = r2_score(y_train, lasso_train_pred)
tested_r2 = r2_score(y_test, laaso_test_pred)

print(mea)
print(mse)
print(rmse)
print(trained_r2)
print(tested_r2)

4185.975017105971
35631696.79010649
5969.229162136975
0.7264414735303193
0.8060924078272595

In [141]:
for feature, coefficient in zip(x_train.columns, lasso_model.coef_):
    print(feature, ":", coefficient)

age : 245.71104337002964
bmi : 306.5082213639186
sex_female : 90.44183961117662
sex_male : -0.0
smoker_no : -21934.50042405131
smoker_yes : 1.4308762960630686e-10
age_smoker : 29.810999866832102

In [152]:
# ElasticNet model
ela_model = ElasticNet(alpha=100,l1_ratio=0.5)
ela_model.fit(x_train,y_train)

ela_pred = ela_model.predict(x_test)

In [153]:
for feature, coefficient in zip(x_train.columns,ela_model.coef_):
    print(feature, ":", coefficient)
print("intercept:",ela_model.intercept_)

age : 130.45752832359122
bmi : 136.29523980108937
sex_female : -0.1523204079806181
sex_male : 0.15233136282650356
smoker_no : -17.096097401971225
smoker_yes : 17.096173998846123
age_smoker : 450.6083889367624
intercept: 326.4193105526574

In [154]:
mea = mean_absolute_error(y_test,ela_pred)
mse = mean_squared_error(y_test, ela_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, ela_pred)

print(mea)
print(mse)
print(rmse)
print(r2)

5175.293625959052
53777827.942917995
7333.336753683005
0.707341213916409